---
- name: Install the prerequisites
  become: true
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present

- name: Import the Grafana GPG key
  become: true
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key

- name: Add Grafana APT repository
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/grafana.list
    line: 'deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main'
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Install grafana
  become: true
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Enable and start the Grafana Service
  become: true
  systemd_service:
    name: grafana-server
    daemon_reload: true
    enabled: true
    state: started