---
- name: Install and Configure Monitoring Stack
  hosts: all
  tasks:
    - name: Prometheus Role
      include_role:
        name: prometheus
      when: inventory_hostname in groups["prometheus"]

    - name: Node Exporter Role
      include_role:
        name: node_exporter
      when: inventory_hostname in groups["node_exporter"]

    - name: Grafana role
      include_role:
        name: grafana
      when: inventory_hostname in groups["grafana"]

    - name: Loki role
      include_role:
        name: loki
      when: inventory_hostname in groups["loki"]

    - name: Black Box Exporter role
      include_role:
        name: blackbox_exporter
      when: inventory_hostname in groups["blackbox_exporter"]

    - name: Apache SSL role
      include_role:
        name: apache_ssl
      when: inventory_hostname in groups["apache_ssl"] 

    # - name: Promtail role
    #   include_role:
    #     name: promtail
    #   when: inventory_hostname in groups["promtail"]
