---
- name: Download the blackbox exporter package
  get_url:
    url: https://github.com/prometheus/blackbox_exporter/releases/download/v0.26.0/blackbox_exporter-0.26.0.linux-amd64.tar.gz
    dest: /tmp/blackbox_exporter.tar.gz

- name: Unzip the archive
  unarchive:
    src: /tmp/blackbox_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy the binary to /usr/local/bin
  become: true
  copy:
    src: /tmp/blackbox_exporter-0.26.0.linux-amd64/blackbox_exporter
    dest: /usr/local/bin/blackbox_exporter
    mode: "0751"
    remote_src: true

- name: Copy the config file to /etc/
  become: true
  copy:
    src: /tmp/blackbox_exporter-0.26.0.linux-amd64/blackbox.yml
    dest: /etc/blackbox.yml
    remote_src: true
    