---
- name: Create a user for Blackbox Exporter
  become: true
  user:
    name: blackbox
    system: true
    shell: /bin/false

- name: Create the service file
  become: true
  copy:
    src: blackbox_exporter.service
    dest: /etc/systemd/system/blackbox_exporter.service

- name: Enable and start the Blackbox Exporter Service
  become: yes
  systemd_service:
    name: blackbox_exporter
    daemon_reload: true
    enabled: true
    state: started