- name: Download node_exporter package
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Unzip the archive
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy the binary to /usr/local/bin
  become: yes
  copy:
    src: /tmp/node_exporter-1.9.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: "0751"
    remote_src: true

- name: Check if node_exporter is installed correctly
  command: node_exporter --version
  register: result
  changed_when: false
  failed_when: result.rc !=0