---
- name: Create a user for prometheus
  become: yes
  user:
    name: prometheus
    system: true
    shell: /bin/false

- name: Change ownership of the prometheus directory
  become: yes
  file:
    path: "{{item}}"
    owner: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Create the service file
  become: yes
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Enable and start the Prometheus Service
  become: yes
  systemd_service:
    name: prometheus
    daemon_reload: true
    enabled: true
    state: started